# Change baseurl before deploy
baseurl = "https://eoinli.github.io"
languageCode = "zh-cn"
paginate = 5
title = "Eoin Lee's Blog"

defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"
