# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "Eoin Lee's Blog"
weight = 1

[zh-tw]
languageName = "繁體中文"
languagedirection = "ltr"
title = "Eoin Lee's Blog"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Eoin Lee's Blog"
weight = 1
